@startuml

'theme 목록 : https://plantuml.com/ko/theme'
!theme vibrant

'skinparam 목록 : https://plantuml.com/ko/skinparam'
skinparam ClassFontSize 16
skinparam ClassFontColor Black
skinparam ClassAttributeFontSize 15
skinparam ArrowColor Black
skinparam ArrowThickness 2

hide empty methods
hide empty fields
hide circle

cloud World {

    rectangle Channel_1 {
        rectangle Room_1 {
            class HostPlayer_1 {
            }
            class Player_2 {
            }
            class Player_3 {
            }


            circle 설명3
            note bottom of 설명3
                각 방에는 1명의 방장을 둔다.
                플레이어가 나갈때마다 들어온 순서대로 방장이 교체된다.

                게임 서버 접속시 TcpSession을 할당받게 된다.
            end note
        }

        rectangle Room_2 {
        }
        rectangle Room_3 {
        }

        rectangle BattleFieldWorker {
        }
        circle 설명2
        note bottom of 설명2
            각 채널은 여러개의 방을 관리한다.
            그리고 채널별로 독립적인 배틀필드 전용을 위한 워커 쓰레드가 있다.
        end note
    }
    circle 설명
    note bottom of 설명
        여러개의 채널을 관리한다.
    end note


    rectangle Channel_2 {
    }
    rectangle Channel_3 {
    }
    rectangle Channel_4 {
    }
    rectangle Channel... {
    }
}

class SystemWorker {
    서버의 정보사항 확인, 서버 종료를 위한
    사용자 입력을 받는다.
}


class GameServer {
    Player 접속을 받는다.
}


@enduml
