/*
 * 작성자: 윤정도
 * 생성일: 1/22/2023 1:59:32 AM
 * =====================
 * 애니메이션 코드 - action.json 정의
 */


#pragma once


// ==================================================================
// 거너 베이스 애니메이션
// ==================================================================

#define DEF_ANIMATION_GUNNER_IDLE_BREATH				1
#define DEF_ANIMATION_GUNNER_IDLE_GUN_ROLLING			2
#define DEF_ANIMATION_GUNNER_WALK						3
#define DEF_ANIMATION_GUNNER_RUN						4
#define DEF_ANIMATION_GUNNER_SLIDING					5
#define DEF_ANIMATION_GUNNER_SHOT_RIGHT_BEGIN			6
#define DEF_ANIMATION_GUNNER_SHOT_RIGHT_SHOT			7
#define DEF_ANIMATION_GUNNER_SHOT_RIGHT_DOWN_BEGIN		9
#define DEF_ANIMATION_GUNNER_SHOT_RIGHT_DOWN_SHOT		10
#define DEF_ANIMATION_GUNNER_SHOT_LEFT					12
#define DEF_ANIMATION_GUNNER_SHOT_LEFT_DOWN				13

#define DEF_ANIMATION_GUNNER_JUMP_START					14
#define DEF_ANIMATION_GUNNER_JUMP_UP					15
#define DEF_ANIMATION_GUNNER_JUMP_DOWN					16
#define DEF_ANIMATION_GUNNER_JUMP_END					17

#define DEF_ANIMATION_GUNNER_JUMP_SHOT_BEGIN			18
#define DEF_ANIMATION_GUNNER_JUMP_SHOT_SHOT				19
#define DEF_ANIMATION_GUNNER_JUMP_SHOT_END				20

#define DEF_ANIMATION_GUNNER_HIT_SMALL					21
#define DEF_ANIMATION_GUNNER_HIT_BIG					22

#define DEF_ANIMATION_GUNNER_FALL_DOWN_BEGIN			23
#define DEF_ANIMATION_GUNNER_FALL_DOWN_BOUNCE			24
#define DEF_ANIMATION_GUNNER_FALL_DOWN_END				25

#define DEF_ANIMATION_GUNNER_SIT						26


// ==================================================================
// 몬스터 베이스 애니메이션
// ==================================================================

#define DEF_ANIMATION_MONSTER_GOBLIN_IDLE				1
#define DEF_ANIMATION_MONSTER_GOBLIN_ATTACK				2
#define DEF_ANIMATION_MONSTER_GOBLIN_HIT_SMALL			3
#define DEF_ANIMATION_MONSTER_GOBLIN_HIT_BIG			4
#define DEF_ANIMATION_MONSTER_GOBLIN_WALK				5
#define DEF_ANIMATION_MONSTER_GOBLIN_FALL_DOWN_BEGIN	6
#define DEF_ANIMATION_MONSTER_GOBLIN_FALL_DOWN_BOUNCE	7
#define DEF_ANIMATION_MONSTER_GOBLIN_FALL_DOWN_END		8
#define DEF_ANIMATION_MONSTER_GOBLIN_SIT				9