/*
 * 작성자: 윤정도
 * 생성일: 6/18/2023 1:57:59 AM
 * =====================
 * 로그 헤더 앞에 붙일 문자열
 * 로고(Logo)처럼 어떤 프로세스인지 한눈에 구분할 수 있도록 하기 위한 문자열
 */


#pragma once


#include <JCore/Utils/Console.h>

#define LOG_SPECIFIER_CLIENT	CSI VT_RESET CSI_GRAPHIC_RENDITION_END "( " CSI VT_FORE_COLOR_LIGHT_BLUE	CSI_GRAPHIC_RENDITION_END "★" CSI VT_RESET CSI_GRAPHIC_RENDITION_END " )"
#define LOG_SPECIFIER_AUTH		CSI VT_RESET CSI_GRAPHIC_RENDITION_END "( " CSI VT_FORE_COLOR_LIGHT_RED		CSI_GRAPHIC_RENDITION_END "A" CSI VT_RESET CSI_GRAPHIC_RENDITION_END " )"
#define LOG_SPECIFIER_CENTER	CSI VT_RESET CSI_GRAPHIC_RENDITION_END "( " CSI VT_FORE_COLOR_CYAN			CSI_GRAPHIC_RENDITION_END "C" CSI VT_RESET CSI_GRAPHIC_RENDITION_END " )"
#define LOG_SPECIFIER_LOBBY		CSI VT_RESET CSI_GRAPHIC_RENDITION_END "( " CSI VT_FORE_COLOR_LIGHT_GREEN	CSI_GRAPHIC_RENDITION_END "L" CSI VT_RESET CSI_GRAPHIC_RENDITION_END " )"
#define LOG_SPECIFIER_GAME		CSI VT_RESET CSI_GRAPHIC_RENDITION_END "( " CSI VT_FORE_COLOR_LIGHT_MAGNETA	CSI_GRAPHIC_RENDITION_END "G" CSI VT_RESET CSI_GRAPHIC_RENDITION_END " )"
