/*
 * 작성자: 윤정도
 * 생성일: 1/23/2023 8:31:53 AM
 * =====================
 * projectile.json
 */


#pragma once


#define DEF_PROJECTILE_GUNNER_AUTO_RIGHT			1
#define DEF_PROJECTILE_GUNNER_AUTO_LEFT				2
#define DEF_PROJECTILE_GUNNER_AUTO_RIGHT_DOWN		3
#define DEF_PROJECTILE_GUNNER_AUTO_LEFT_DOWN		4
#define DEF_PROJECTILE_GUNNER_AUTO_JUMP_RIGHT		5
#define DEF_PROJECTILE_GUNNER_AUTO_JUMP_LEFT		6
