<Project>
	<PropertyGroup>
		<BaseIntermediateOutputPath>$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)..\Projects\$(MSBuildProjectName)\Intermediate\'))\</BaseIntermediateOutputPath>
		<BaseOutputPath>$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)..\Projects\$(MSBuildProjectName)\Output\'))\</BaseOutputPath>
	</PropertyGroup>
</Project>
