/*
 * 작성자: 윤정도
 * 생성일: 1/23/2023 8:31:53 AM
 * =====================
 *
 */


#pragma once


#define GUNNER_PROJECTILE_AUTO_RIGHT			1
#define GUNNER_PROJECTILE_AUTO_LEFT				2
#define GUNNER_PROJECTILE_AUTO_RIGHT_DOWN		3
#define GUNNER_PROJECTILE_AUTO_LEFT_DOWN		4
#define GUNNER_PROJECTILE_AUTO_JUMP_RIGHT		5
#define GUNNER_PROJECTILE_AUTO_JUMP_LEFT		6
